server:
  port: 8081
  tomcat:
    max-connections: 200         # ?? ?? ?? ?

#?? ??? ?? ??
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100GB          # ??? ? ? ?? ? ?? ??
      max-request-size: 100MB       # ??? ??? ? ??
  web:
    resources:
      static-locations: file:///C:/uploadFiles/    # ?? ??? ??
      cache-period: 3600                          # ? ????? ?? ??(?, 1??)


filepath: C:\\uploadFiles

